// <auto-generated />
namespace Graduation_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editDatatypepricefromdoubletodecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editDatatypepricefromdoubletodecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202004121107355_editDatatypepricefromdoubletodecimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
